spring:
  application:
    name: dsp-server
server:
  port: 3333
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

logging:
  level:
    com.github.ruifengho: DEBUG

dsp:
  transaction:
    netty:
      host: 127.0.0.1
      heart: 5
      port: 6666
      delaytime: 3      